---
- name: All test cases - Fixed version
  hosts: localhost
  connection: local
  
  tasks:
    - name: Case 1 - Simple string JSON
      my_own_namespace.yandex_cloud_elk.yandex_auth_test:
        service_account_key: '{"id": "case1"}'
        folder_id: "b1gcase1"
      register: case1
    
    - name: Case 2 - YAML dict
      my_own_namespace.yandex_cloud_elk.yandex_auth_test:
        service_account_key:
          id: "case2-id"
          account: "case2-account"
        folder_id: "catcase2"
      register: case2
    
    - name: Case 3 - Invalid JSON (should fail gracefully)
      my_own_namespace.yandex_cloud_elk.yandex_auth_test:
        service_account_key: "not-a-json-at-all"
        folder_id: "b1gcase3"
      register: case3
    
    - name: Case 4 - JSON with escaped quotes
      my_own_namespace.yandex_cloud_elk.yandex_auth_test:
        service_account_key: '{\"id\": \"case4\", \"test\": true}'
        folder_id: "ajecase4"
      register: case4
    
    - name: Results summary
      debug:
        msg: |
          === Test Results ===
          Case 1 (Simple JSON): {{ case1.authenticated }} - {{ case1.message }}
          Case 2 (YAML dict): {{ case2.authenticated }} - SA ID: {{ case2.service_account_id | default('None') }}
          Case 3 (Invalid JSON): Auth={{ case3.authenticated }}, Valid={{ case3.validation_passed }}, Msg={{ case3.message }}
          Case 4 (Escaped JSON): {{ case4.authenticated }} - {{ case4.message }}
