---
- name: Simple JSON test
  hosts: localhost
  connection: local
  
  tasks:
    - name: Test with simple JSON
      my_own_namespace.yandex_cloud_elk.yandex_auth_test:
        service_account_key: '{"id": "test-123", "name": "test"}'
        folder_id: "b1gtestfolder123"
      register: result
    
    - debug:
        var: result
